# Generated by Django 4.2.30 on 2026-07-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_booking_remove_item_category_remove_review_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('tattoo', 'Tattoo'), ('piercing', 'Piercing')], max_length=20),
        ),
    ]
