# Generated by Django 4.2.30 on 2026-06-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='Silver', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(default='Titanium', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default='1.2mm (16g)', max_length=50),
        ),
    ]
